# Generated by Django 4.1.4 on 2022-12-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monedero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.PositiveBigIntegerField()),
                ('cantidad', models.PositiveIntegerField()),
                ('limite', models.PositiveIntegerField()),
                ('descuento', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='bank_account',
            field=models.PositiveBigIntegerField(),
        ),
    ]
