# Generated by Django 4.1.4 on 2022-12-22 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_monedero_alter_usuario_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monedero',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.usuario'),
        ),
    ]
