# Generated by Django 4.1.4 on 2022-12-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_id_usuario_monedero_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='bank_account',
            field=models.CharField(max_length=20),
        ),
    ]
